### PR TITLE
Fixes #160: Changing subnets in ASG breaks the update

### LINKED ISSUE #160: Changing subnets in ASG breaks the update
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Caused by: Unexpected error: software.amazon.awssdk.services.autoscaling.model.AutoScalingException: The availability zones of the specified subnets and the Auto Scaling group <span class="code-keyword">do</span> not match (Service: AutoScaling, Status Code: 400, Request ID: f8fd6e33-df1b-11e9-8637-a34c157086fe)
</pre>
</div></div>

<p>It looks like the issue is that availability zones are saved to state even if they were not provided by the user. Then on update they get filled in but don't match subnets.</p>
<i>[GYRO-407] created by jcollins</i>

[GYRO-407]: https://perfectsense.atlassian.net/browse/GYRO-407

### PR DESCRIPTION
**Pull request by deepanjan90**
Updating subnet throws an error if availability zone is not set and the updated subnet's availability zone is different than the previously configured subnet's availability zone.

The reason for this was that the availability zone was saved in state even if not configured.

This fixes it by only setting the availability zone if configured.

### CODE REVIEW

File: src/main/java/gyro/aws/autoscaling/AutoScalingGroupResource.java [hunk 1]
```diff
@@ -650,13 +650,18 @@ public boolean refresh() {
         }
 
         boolean isDesiredCapacitySet = getDesiredCapacity() != null;
+        boolean isAvailabilityZoneSet = !getAvailabilityZones().isEmpty();
```
Comment (beetlebugorg) [inline src/main/java/gyro/aws/autoscaling/AutoScalingGroupResource.java]: Curious why we're setting a boolean, then using it once, rather than just put this expression in the `if` directly?
