### PR TITLE
Catch exception if hosted zone is not found

### LINKED ISSUE #404: Route53 Record Set deleted from the console causes a refresh error
STR:

 - Create a Route 53 record set using gyro.
 - Delete the record set from the console.
 - Refreshing the resource causes an error
 
 ```
 Error: Can't refresh aws::route53-record-set frontend-elb resource!
Caused by: Unexpected error: software.amazon.awssdk.services.route53.model.NoSuchHostedZoneException: No hosted zone found with ID: Z04056192BINSLDIWP56P (Service: Route53, Status Code: 404, Request ID: 9e5d2213-7909-45e3-ad87-31fedefedcc0, Extended Request ID: null)
```

Should instead refresh and ask to create the record set again.

### PR DESCRIPTION
**Pull request by harjain99**
Fixes #404

### CODE REVIEW

File: src/main/java/gyro/aws/route53/RecordSetResource.java [hunk 1]
```diff
@@ -434,17 +436,21 @@ public void delete(GyroUI ui, State state) {
...
-                .filter(o -> o.type().name().equalsIgnoreCase(getType()))
-                .findFirst()
-                .orElse(null);
+        try {
+            List<ResourceRecordSet> records = client.listResourceRecordSetsPaginator(
+                r -> r.hostedZoneId(getHostedZone().getId())
+            ).resourceRecordSets().stream().collect(Collectors.toList());
+
+            if (!records.isEmpty()) {
+                return records
```
Comment (deepanjan90) [inline src/main/java/gyro/aws/route53/RecordSetResource.java:445]: Refactor the code to have a single return from the method.

**Review by deepanjan90 — CHANGES_REQUESTED** [review]
Looks good, 1 minor refactor requested.

**Review by deepanjan90 — APPROVED** [review]
