### PR TITLE
Fixed validation of read and write capacities

### LINKED ISSUE #642: Fix DynamoDB Validation. Fails on valid PAY_PER_REQUEST Table and allows incorrect PROVISIONED tables
Currently, the validation only checks for `null` values in the `readCapacity` and `writeCapacity` fields (both for `PROVISIONED` and `PAY_PER_REQUEST` billing modes).

However, a `DescribeTableRequest` will return a `0` (zero) value for both `readCapacity` and `writeCapacity` for non-provisioned tables, which will fail the validation of a `PAY_PER_REQUEST` table.

Furthermore, a `0` (zero) value for `readCapacity` and `writeCapacity` will pass validation, whereas those values are below the minimum required values for a `PROVISIONED` table (see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#default-limits-throughput-capacity-modes).

### PR DESCRIPTION
**Pull request by aftenkap**
resolves #642 

Currently, the validation only checks for `null` values in the `readCapacity` and `writeCapacity` fields (both for `PROVISIONED` and `PAY_PER_REQUEST` billing modes).

_However_, a `DescribeTableRequest` will return a `0` (zero) value for both `readCapacity` and `writeCapacity`, which will fail the validation of a `PAY_PER_REQUEST` table.

Furthermore, a `0` (zero) value for `readCapacity` and `writeCapacity` will _pass_ validation, whereas those values are below the minimum required values for a `PROVISIONED` table (see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#default-limits-throughput-capacity-modes).

This PR updates the checks to validate a non-zero, positive value for `PROVISIONED` tables and a null or smaller or equal to zero value for `PAY_PER_REQUEST` tables.

### CODE REVIEW

File: src/main/java/gyro/aws/dynamodb/DynamoDbTableResource.java [hunk 1]
```diff
@@ -591,14 +591,14 @@ public void delete(GyroUI ui, State state) throws Exception {
     public List<ValidationError> validate(Set<String> configuredFields) {
         List<ValidationError> errors = new ArrayList<>();
 
-        if ("PROVISIONED".equals(getBillingMode()) && (getReadCapacity() == null || getWriteCapacity() == null)) {
+        if ("PROVISIONED".equals(getBillingMode()) && (getReadCapacity() == null || getWriteCapacity() == null || getReadCapacity() <= 0L || getWriteCapacity() <= 0L)) {
```
Comment (deepanjan90) [inline src/main/java/gyro/aws/dynamodb/DynamoDbTableResource.java:594]: For this one to validate the minimum value of the fields.
Rather than doing it explicitly in the `validate()` we can use `@Min(1)` annotation on the `getter()` of those fields.

This will explicitly tell the use of a minimum value, as well as this will automatically flow in the gyro docs for the same as well.

Comment (deepanjan90) [reply src/main/java/gyro/aws/dynamodb/DynamoDbTableResource.java:594]: This change should also be done for `DynamoDbGlobalSecondaryIndex`

File: src/main/java/gyro/aws/dynamodb/DynamoDbTableResource.java [hunk 2]
```diff
@@ -591,14 +591,14 @@ public void delete(GyroUI ui, State state) throws Exception {
...
             errors.add(new ValidationError(
                 this,
                 null,
                 "'read-capacity' and 'write-capacity' must both be provided when 'billing-mode' is set to 'PROVISIONED'!"));
         }
 
-        if ("PAY_PER_REQUEST".equals(getBillingMode()) && (getReadCapacity() != null || getWriteCapacity() != null)) {
+        if ("PAY_PER_REQUEST".equals(getBillingMode()) && ((getReadCapacity() != null && getReadCapacity() > 0) || (getWriteCapacity() != null && getWriteCapacity() > 0))) {
```
Comment (deepanjan90) [inline src/main/java/gyro/aws/dynamodb/DynamoDbTableResource.java:601]: This change should also be done for `DynamoDbGlobalSecondaryIndex`

**Review by deepanjan90 — CHANGES_REQUESTED** [review]
Minor changes that helps in doc generation and another place where we need this to be applied.

**Review by deepanjan90 — APPROVED** [review]
